server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: admin
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true

  rabbitmq:
    addresses: amqp://leyou:123456@192.168.40.77
    virtual-host: /leyou
    template:
      retry:
        enabled: true # 开启失败重试
        initial-interval: 10000ms # 第一次的重试时间间隔
        max-interval: 300000ms # 最长重试间隔，超过这个间隔将不再重试
        multiplier: 2 # 下次重试间隔的倍数
      exchange: ly.item.exchange # 缺省的交换机名称
    #    publisher-confirms: true # 过时弃用，使用publisher-confirm-type: correlated
    publisher-confirm-type: correlated
  redis:
    host: 192.168.40.77
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.leyou.item.bean
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
ly:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: F:/BadCode/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000