server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    addresses: amqp://leyou:123456@192.168.40.77
    virtual-host: /leyou

ly:
  sms:
    accessKeyId: ************* # 你自己的accessKeyId
    accessKeySecret: **************** # 你自己的AccessKeySecret
    signName: ********* # 签名名称
    verifyCodeTemplate: ************* # 模板名称
