server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: admin
  rabbitmq:
    addresses: amqp://leyou:123456@192.168.40.77
    virtual-host: /leyou
    template:
      retry:
        enabled: true # 开启失败重试
        initial-interval: 10000ms # 第一次的重试时间间隔
        max-interval: 300000ms # 最长重试间隔，超过这个间隔将不再重试
        multiplier: 2 # 下次重试间隔的倍数
      exchange: ly.item.exchange # 缺省的交换机名称
#    publisher-confirms: true # 过时弃用，使用publisher-confirm-type: correlated
    publisher-confirm-type: correlated
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}